#:schema https://raw.githubusercontent.com/YunoHost/apps/main/schemas/manifest.v2.schema.json

packaging_format = 2

id = "linkace"
name = "LinkAce"
description.en = "Self-hosted archive to collect links of your favorite websites"
description.fr = ""

version = "2.4.1~ynh1"

maintainers = ["trendless"]

[upstream]
license = "GPL-3.0-or-later"
website = "https://www.linkace.org"
demo = "https://demo.linkace.org"
admindoc = "https://www.linkace.org/docs/v2"
userdoc = "https://www.linkace.org/docs/v2/application/dashboard"
code = "https://github.com/Kovah/LinkAce"

[integration]
yunohost = ">= 12.1.11"
helpers_version = "2.1"
architectures = "all"
multi_instance = true

ldap = false
sso = false

disk = "250M"
ram.build = "200M"
ram.runtime = "150M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.admin]
    type = "user"

[resources]

    [resources.sources]
        [resources.sources.main]
        url = "https://github.com/Kovah/LinkAce/archive/refs/tags/v2.4.1.tar.gz"
        sha256 = "f42063068e21a5f3c5cb69c582f69fd008f3f1bd178712cc94392a7f03b669ba"
        autoupdate.strategy = "latest_github_tag"

    [resources.system_user]
    allow_email = true

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"

    [resources.apt]
    packages = "mariadb-server, redis-server, php8.4-bcmath, php8.4-ctype, php8.4-dom, php8.4-fileinfo, php8.4-mbstring, php8.4-pdo, php8.4-tokenizer, php8.4-xml"

    [resources.database]
    type = "mysql"
